# Generated by Django 5.0 on 2024-01-09 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('identifier', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(11)])),
                ('url', models.IntegerField()),
            ],
        ),
    ]
