# Generated by Django 5.0 on 2024-01-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.CharField(max_length=120),
        ),
    ]
